a = input('enter first number= ')
b = input('enter 2nd number= ')
print(int(a) + int(b))
A = int(input('enter your age'))
B = int(input('enter your salary'))
print(str(A) + str(B))
print(float((str(A) + str(B))))
z = float((str(A) + str(B)))
print(bool(z))
print("RKSGALAXY")